/*-------------------------------------------------------------------------
ScannerOutput.cs -- Generation of the Recursive Descent Parser
Compiler Generator Coco/R to F#,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
with improvements by Pat Terry, Rhodes University

Extended to produce F# version by Alexandre Pereira 
University of Beira Interior, Portugal.

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/

#pragma warning disable 0414
#pragma warning disable 0219

using System;
using System.IO;
using System.Text;
using System.Collections;

namespace at.jku.ssw.Coco {
    public class ScannerOutput
    {
	public StreamWriter gen;
	public Tab tab;
	public bool ignoreCase;
	public bool hasCtxMoves;
	public State firstState;
	public Comment firstComment;
	private Hashtable keywords=new Hashtable();

	public ScannerOutput(StreamWriter gen, Tab tab, bool ignoreCase, bool hasCtxMoves, State firstState, Comment firstComment) {
	    this.gen=gen;
	    this.tab=tab;
	    this.ignoreCase=ignoreCase;
	    this.hasCtxMoves=hasCtxMoves;
	    this.firstState=firstState;
	    this.firstComment=firstComment;
   	    keywords.Add("-->namespace",GenNamespace());
	    keywords.Add("-->declarations",GenDeclarations());
	    keywords.Add("-->initialization",GenInitialization());
	    keywords.Add("-->casing1",GenCasing1());
	    keywords.Add("-->casing2",GenCasing2());
	    keywords.Add("-->comments",GenComments());
	    keywords.Add("-->literals",GenLiterals());
        keywords.Add("-->scan3", GenScan3());
        keywords.Add("-->scan1",GenScan1());
	    keywords.Add("-->scan2",GenScan2());
	    keywords.Add("$$$",GenDollarDollarDollar());
	}
	

	public void dispatch(String cmd)
	{
	    if(keywords.Contains(cmd))
		gen.Write(keywords[cmd]);
	    else
		Console.WriteLine(String.Format("Undefined insertion point {0}.",cmd)); // pf: should be an error!
	}
	//---------- Output primitives
	private string Ch(char ch) {
	    if (ch < ' ' || ch >= 127 || ch == '\'' || ch == '\\') return  Convert.ToString((int)ch);
	    else return String.Format("int '{0}'", ch);
	}

        private string Ch(int ch)
        {
            if (ch < ' ' || ch >= 127 || ch == '\'' || ch == '\\') return Convert.ToString(ch);
            else return String.Format("{0}", ch);
        }
	
	private string ChCond(char ch) {
	    return String.Format("ch = {0}", Ch(ch));
	}


        private void PutRange(CharSet s)
        {
            for (CharSet.Range r = s.head; r != null; r = r.next)
            {
                if (r.from == r.to) { gen.Write("ch = " + Ch(r.from)); }
                else if (r.from == 0) { gen.Write("ch <= " + Ch(r.to)); }
                else { gen.Write("ch >= " + Ch(r.from) + " && ch <= " + Ch(r.to)); }
                if (r.next != null) gen.Write(" || ");
            }
        }

	private void PutRange(BitArray s) {
	    int[] lo = new int[32];  
	    int[] hi = new int[32];
	    // fill lo and hi
        int max = CharClass.charSetSize;
        
	    int top = -1;
	    int i = 0;
	    while (i < max) {
		if (s[i]) {
		    top++; lo[top] = i; i++;
		    while (i < max && s[i]) i++;
		    hi[top] = i-1;
		} else i++;
	    }
	    // print ranges
	    if (top == 1 && lo[0] == 0 && hi[1] == max-1 && hi[0]+2 == lo[1]) {
		BitArray s1 = new BitArray(max); s1[hi[0]+1] = true;
		gen.Write("not"); PutRange(s1); gen.Write(" && ch <> EOF");
	    } else {
		gen.Write("(");
		for (i = 0; i <= top; i++) {
		    if (hi[i] == lo[i]) gen.Write("ch = {0}", Ch((char)lo[i]));
		    else if (lo[i] == 0) gen.Write("ch <= {0}", Ch((char)hi[i]));
		    else gen.Write("ch >= {0} && ch <= {1}", Ch((char)lo[i]), Ch((char)hi[i]));
		    if (i < top) gen.Write(" || ");
		}
		gen.Write(")");
	    }
	}

	//------------------------ scanner generation ----------------------


        static string Tabs(int n) { return new string('\t', n); }

        void GenComBody(Comment com, int indent) {
            gen.WriteLine("{0}while more.Value && ch <> EOF do", Tabs(indent));
            gen.WriteLine("{0}if ({1})", Tabs(indent + 1), ChCond(com.stop[0]));
            gen.WriteLine("{0}then (", Tabs(indent + 1));

            if (com.stop.Length == 1) {
                gen.WriteLine("{0}level.Value <- post_dec level.Value;", Tabs(indent + 2));
                gen.WriteLine("{0}if level.Value = 0 then (", Tabs(indent + 2));
                gen.WriteLine("{0}oldEols <- line - line0;", Tabs(indent + 3));
                gen.WriteLine("{0}x.NextCh();", Tabs(indent + 3));
                gen.WriteLine("{0}result.Value <- true;", Tabs(indent + 3));
                gen.WriteLine("{0}more.Value <- false )", Tabs(indent + 3));
            } else {
                gen.WriteLine("{0}x.NextCh();", Tabs(indent + 2));
                gen.WriteLine("{0}if ({1}) then (", Tabs(indent + 2), ChCond(com.stop[1]));
                gen.WriteLine("{0}level.Value <- post_dec level.Value;", Tabs(indent + 3));
                gen.WriteLine("{0}if level.Value = 0 then (", Tabs(indent + 3));
                gen.WriteLine("{0}oldEols <- line - line0;", Tabs(indent + 4));
                gen.WriteLine("{0}x.NextCh();", Tabs(indent + 4));
                gen.WriteLine("{0}result.Value <- true;", Tabs(indent + 4));
                gen.WriteLine("{0}more.Value <- false )", Tabs(indent + 4));
                gen.WriteLine("{0}else x.NextCh();", Tabs(indent + 3));
                gen.WriteLine("{0})", Tabs(indent + 2));
            }

            if (com.nested) {
                gen.WriteLine("{0}) else if ({1}) then (", Tabs(indent + 1), ChCond(com.start[0]));
                if (com.start.Length == 1)
                    gen.WriteLine("{0}level.Value <- post_inc level.Value; x.NextCh();", Tabs(indent + 2));
                else {
                    gen.WriteLine("{0}x.NextCh();", Tabs(indent + 2));
                    gen.WriteLine("{0}if ({1}) then (", Tabs(indent + 2), ChCond(com.start[1]));
                    gen.WriteLine("{0}level.Value <- post_inc level.Value; x.NextCh();", Tabs(indent + 3));
                    gen.WriteLine("{0})", Tabs(indent + 2));
                }
            }
            gen.WriteLine("{0}) else x.NextCh();", Tabs(indent + 1));
            gen.WriteLine("{0}result.Value;", Tabs(indent));
        }


        void GenComment(Comment com, int i) {
            gen.WriteLine();
            gen.WriteLine("\tmember x.Comment{0}() =", i);
            gen.WriteLine("\t\tlet level = ref 1");
            gen.WriteLine("\t\tlet line0 = line");
            gen.WriteLine("\t\tlet lineStart0 = lineStart");
            gen.WriteLine("\t\tlet more = ref true");
            gen.WriteLine("\t\tlet result = ref false");
            gen.WriteLine("\t\tlet pos0 = buffer.pos");
            gen.WriteLine("\t\tlet ch0 = ch");
            if (com.start.Length == 1) {
                gen.WriteLine("\t\tx.NextCh();");
                GenComBody(com, 2);
            } else {
                gen.WriteLine("\t\tx.NextCh();");
                gen.WriteLine("\t\tif ({0})", ChCond(com.start[1]));
                gen.WriteLine("\t\tthen (");
                gen.WriteLine("\t\t\tx.NextCh();");
                GenComBody(com, 3);
                gen.WriteLine("\t\t) else (");
                gen.WriteLine("\t\t\tlineStart <- lineStart0;");
                gen.WriteLine("\t\t\tbuffer.pos <- pos0;");
                gen.WriteLine("\t\t\tch <- ch0;");
                gen.WriteLine("\t\t\tline <- line0;");
                gen.WriteLine("\t\t\tfalse )");

            }
            gen.WriteLine("\t");
        }

		
	string SymName(Symbol sym) {
	    if (Char.IsLetter(sym.name[0])) { // real name value is stored in Tab.literals
		foreach (DictionaryEntry e in tab.literals)
		    if ((Symbol)e.Value == sym) return (string)e.Key;
	    }
	    return sym.name;
	}
	
	void GenXLiterals() {
	    if (ignoreCase) {
            gen.WriteLine("\t\tmatch lit.ToLower() with \n");
	    } else {
		gen.WriteLine("\t\tmatch lit with\n");
	    }
	    foreach (Symbol sym in tab.terminals) {
		if (sym.tokenKind == Symbol.litToken) {
		    string name = SymName(sym);
		    if (ignoreCase) name = name.ToLower();
		    // sym.name stores literals with quotes, e.g. "\"Literal\""
		    gen.WriteLine("\t\t\t| {0} -> {1} \n", name, sym.n);
		}
	    }
	    gen.WriteLine("\t\t\t| _ -> def ");
	}
	
	void WriteState(State state) {
	    Symbol endOf = state.endOf;
	    gen.WriteLine("\t\t| {0} -> ", state.nr);
	    bool ctxEnd = state.ctx;
	    for (Action action = state.firstAction; action != null; action = action.next) {
		if (action == state.firstAction) gen.Write("\t\t\t\tif (");
		else gen.Write("\t\t\t\telse if (");
        if (action.typ == Node.chr)
        {
           gen.Write(ChCond((char)action.sym));
        }
        else
        {
            //Convert Charset to BitArray
            CharSet teste2 = tab.CharClassSet(action.sym);
            bool[] cg = new bool[256];
            for (int i = 0; i < 256; i++) cg[i] = teste2[i];
            BitArray cc = new BitArray(cg);
            PutRange(cc);
        }
		gen.Write(") then (");
		if (action.tc == Node.contextTrans) {
		    gen.Write("apx.Value <- apx+1; "); ctxEnd = false;
		} else if (state.ctx)
		    gen.Write("apx.Value <- 0; ");
		gen.Write("x.AddCh(); x.resolveKind {0};", action.target.state.nr);
		gen.WriteLine(")");
	    }
	    if (state.firstAction == null)
		gen.Write("\t\t\t\t(");
	    else
		gen.Write("\t\t\t\telse (");
	    if (ctxEnd) { // final context state: cut appendix
		gen.WriteLine();
		gen.WriteLine("\t\t\t\t\ttlen.Value <- tlen- apx;");
		gen.WriteLine("\t\t\t\t\tpos.Value <- pos - apx - 1; line = t.line;");
		gen.WriteLine("\t\t\t\t\tbuffer.Pos.Value <- pos + 1; x.NextCh();");
		gen.Write("\t\t\t\t\t");
	    }
	    if (endOf == null) {
		gen.WriteLine(" noSym )");
	    } else {

		if (endOf.tokenKind == Symbol.classLitToken) {
            gen.Write("x.checkLiteral (tval.ToString()) ");
            gen.WriteLine(" {0} )", endOf.n);
		} else {
            gen.Write(" {0} ", endOf.n); 
            gen.WriteLine(")");
		  
		}
	    }
	}

	void FillStartTab(int[] startTab) {
	    for (Action action = firstState.firstAction; action != null; action = action.next) {
		int targetState = action.target.state.nr;
        if (action.typ == Node.chr) startTab[action.sym] = targetState;
		else {
            //Convert the charset to a bitarray          
            CharSet teste2 = tab.CharClassSet(action.sym);
            bool[] cg = new bool[256];
            for (int i = 0; i < 256; i++) cg[i] = teste2[i];
            BitArray cc = new BitArray(cg);
		    for (int i = 0; i < cc.Count; i++)
			if (cc[i]) startTab[i] = targetState;
		}
	    }
	}
	String GenNamespace() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    if (tab.nsName != null && tab.nsName.Length > 0) {
            gen.WriteLine("module {0}.Scanner", tab.nsName);
            gen.WriteLine();
	    }
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenDeclarations() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    int[] startTab = new int[CharClass.charSetSize];
	    FillStartTab(startTab);
	    gen.WriteLine("let charSetSize = {0}", CharClass.charSetSize);
	    gen.WriteLine("\tlet maxT = {0}", tab.terminals.Count - 1);
            gen.WriteLine("\tlet noSym = {0}", tab.noSym.n);
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);	    
	    gen=oldGen;
	    return reader.ReadToEnd();
	}

        void WriteStart()//Write Start Tab
        {
            // Leading newline so frame-provided indent on the marker line becomes a blank line;
            // all generated lines use 5 tabs to match the -->initialization context in the frame.
            gen.WriteLine();
            for (Action action = firstState.firstAction; action != null; action = action.next)
            {
                int targetState = action.target.state.nr;
                if (action.typ == Node.chr)
                {
                    gen.WriteLine("\t\t\t\t\tstart.Add(" + action.sym + "," + targetState + "); ");
                }
                else
                {
                    CharSet s = tab.CharClassSet(action.sym);
                    for (CharSet.Range r = s.head; r != null; r = r.next)
                    {
                        gen.Write("\t\t\t\t\tfor i = " + r.from + " to " + r.to + " do ");
                        gen.WriteLine("start.Add(i,"  + targetState + ")");
                    }
                }
            }
            gen.WriteLine("\t\t\t\t\tstart.Add(65535+1, -1);");
        }


	String GenInitialization() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
        Comment com = firstComment;
          
	    StreamReader reader=new StreamReader(insertion);

        WriteStart();
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenCasing1() { 
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    if (ignoreCase) {
            gen.WriteLine(";");
        gen.Write("\t\tif (ch <> EOF ) then ch <- int (char.ToLower(char ch))");
	    }
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenCasing2() { 
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
        if (ignoreCase) gen.Write("	ignore(tval.Append(char.ToLower(char ch))); "); else gen.Write("ignore (tval.Append(char ch));");
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenComments() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    Comment com = firstComment; int i = 0;
	    while (com != null) {
		GenComment(com, i);
		com = com.next; i++;
	    }
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);	    
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenLiterals() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    GenXLiterals();
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
	String GenScan1() { 
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    Comment com=firstComment; int i=0;
	    if (firstComment != null) {
		gen.Write("\t\t\tif (");
		while (com != null) {
		    gen.Write(ChCond(com.start[0]));
		    gen.Write(" && x.Comment{0}()", i);
		    if (com.next != null) gen.Write(" || ");
		    com = com.next; i++;
		}
		gen.WriteLine(") then x.NextToken()");
		gen.WriteLine("\t\t\telse");
	    }
	    if (hasCtxMoves) { gen.WriteLine(); gen.Write("\t\t\tlet apx = ref 0"); } // pdt
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}

	String GenScan2() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    for (State state = firstState.next; state != null; state = state.next)
		WriteState(state);
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}


        String GenScan3()
        {
            MemoryStream insertion = new MemoryStream();
            StreamWriter oldGen = gen;
            gen = new StreamWriter(insertion);
            CharSet nt = new CharSet();
            CharSet tt = new CharSet();
            Comment com = firstComment;

            StreamReader reader = new StreamReader(insertion);
   
                    gen.Write(" ");
                    if (tab.ignored.Elements() > 0) { PutRange(tab.ignored); } else { gen.Write("false"); }
                    gen.Write(" ");
           gen.Flush();
            insertion.Seek(0, SeekOrigin.Begin);
            gen = oldGen;
            return reader.ReadToEnd();
        }

	String GenDollarDollarDollar() {
	    MemoryStream insertion=new MemoryStream();
	    StreamWriter oldGen=gen;
	    gen=new StreamWriter(insertion);
	    StreamReader reader=new StreamReader(insertion);
	    gen.Flush();
	    insertion.Seek(0,SeekOrigin.Begin);
	    gen=oldGen;
	    return reader.ReadToEnd();
	}
    }// End ScannerOutput       
}//End Namespace
